# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1APIuYtTT7mgaKkySr8THfcMhUKLeS18t
"""

import pandas as pd
df_csv=pd.read_csv('files1.csv')
df_csv

import pandas as pd
import matplotlib.pyplot as plt

# Read CSV
df_csv = pd.read_csv('files1.csv')

# Clean column names
df_csv.columns = df_csv.columns.str.strip()

# Print actual column names to verify
print(df_csv.columns.tolist())

# Plot using exact column names
plt.figure(figsize=(12, 6))
plt.bar(df_csv['States and Union Territories'], df_csv['No. Of Phases'], color='Blue')
plt.title('Number of Election Phases by State/UT')
plt.xlabel('States and Union Territories')
plt.ylabel('Number of Phases')
plt.xticks(rotation=90)
plt.grid(axis='y')
plt.tight_layout()
plt.show()

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
        return "Error! Division by zero."
    return x / y

def calculator():
    print("Simple Calculator")
    print("Select operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")

    while True:
        choice = input("Enter choice (1/2/3/4 or q to quit): ")
        if choice.lower() == 'q':
            print("Exiting calculator. Goodbye!")
            break

        if choice in ['1', '2', '3', '4']:
            try:
                num1 = float(input("Enter first number: "))
                num2 = float(input("Enter second number: "))
            except ValueError:
                print("Invalid input! Please enter numeric values.")
                continue

            if choice == '1':
                print(f"Result: {add(num1, num2)}")
            elif choice == '2':
                print(f"Result: {subtract(num1, num2)}")
            elif choice == '3':
                print(f"Result: {multiply(num1, num2)}")
            elif choice == '4':
                print(f"Result: {divide(num1, num2)}")
        else:
            print("Invalid choice! Please select a valid operation.")

if __name__ == "__main__":
    calculator()

