# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1APIuYtTT7mgaKkySr8THfcMhUKLeS18t
"""

import pandas as pd
df_csv=pd.read_csv('files1.csv')
df_csv

import pandas as pd
import matplotlib.pyplot as plt

# Read CSV
df_csv = pd.read_csv('files1.csv')

# Clean column names
df_csv.columns = df_csv.columns.str.strip()

# Print actual column names to verify
print(df_csv.columns.tolist())

# Plot using exact column names
plt.figure(figsize=(12, 6))
plt.bar(df_csv['States and Union Territories'], df_csv['No. Of Phases'], color='Blue')
plt.title('Number of Election Phases by State/UT')
plt.xlabel('States and Union Territories')
plt.ylabel('Number of Phases')
plt.xticks(rotation=90)
plt.grid(axis='y')
plt.tight_layout()
plt.show()