# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flx7RqHpfGmPLO16-iId_0CYhn8Nlsh_
"""

print("hello world")

